apiVersion: apps/v1
kind: Deployment
metadata:
  name: aerodb-backend
  labels:
    name: aerodb-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: aerodb-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: aerodb-backend
    spec:
      containers:
      - image: daanrsantiago/aerodb-backend:latest
        imagePullPolicy: IfNotPresent
        name: aerodb-backend-container
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
          - name: MONGODB_USER
            valueFrom:
              secretKeyRef:
                name: segredo-mongodb
                key: username
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: segredo-mongodb
                key: password
          - name: NODE_ENV
            value: production
          - name: NODE_PORT
            value: '80'
          - name: MONGODB_URI
            value: mongodb+srv://mongodb.default.svc.cluster.local/aerodb?ssl=false&replicaSet=rs0&readPreference=secondaryPreferred&authSource=admin